import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {ThemeProvider} from '@/components/theme-provider';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import {Toaster} from '@/components/ui/toaster';
import ConvexClientProvider from './ConvexClientProvider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex relative">
              <Sidebar />
              <div className="w-full overflow-hidden">
                <Navbar />

                {children}
              </div>
            </div>
          </ThemeProvider>
          <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
